apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
spec:
  containers:
  - name: nginx-container
    image: nginx
  tolerations:
  - effect: "NoSchedule"
    key: "spray"
    value: "mortein"
  
#Taint-Toleration
#노드가 받아들일 수 있는 파드를 결정

#노드의 종류
# 일치하는 테인트 : O
# 일치하지 않는 테인트 : X
# 테인트가 없는 노드 : O

# 원하지 않는 노드에 배치되지 않도록 막을수 있지만 
# 원하는 노드에만 배치할 수는 없음

#테인트 생성 kubectl taint node node01 key=value:NoSchedule
#테인트 삭제 kubectl taint node node01 key-